# This file contains the values obtained by the calibration package
# Results are written in the form that they can be directly sent to a static_transform_publisher node
# Recall its usage use static_transform_publisher x y z qx qy qz qw frame_id child_frame_id period(milliseconds) 
translation: [0.00387569, 0.570511, -0.0753643]
rotation: [0.543803, 0.548304, -0.443274, 0.455136]
frame_id: camera_rgb_optical_frame
child_frame_id: vito_anchor
