PotentialFieldControl/Kp_0: 110
PotentialFieldControl/Kp_1: 110
PotentialFieldControl/Kp_2: 110
PotentialFieldControl/Kp_3: 55
PotentialFieldControl/Kp_4: 55
PotentialFieldControl/Kp_5: 55
PotentialFieldControl/Kd_0: 15
PotentialFieldControl/Kd_1: 15
PotentialFieldControl/Kd_2: 15
PotentialFieldControl/Kd_3: 5
PotentialFieldControl/Kd_4: 5
PotentialFieldControl/Kd_5: 5
PotentialFieldControl/Ki_0: 2.0
PotentialFieldControl/Ki_1: 2.0
PotentialFieldControl/Ki_2: 2.0
PotentialFieldControl/Ki_3: 1.0
PotentialFieldControl/Ki_4: 1.0
PotentialFieldControl/Ki_5: 1.0
PotentialFieldControl/use_real: true