PotentialFieldControl/Kp_0: 100
PotentialFieldControl/Kp_1: 100
PotentialFieldControl/Kp_2: 100
PotentialFieldControl/Kp_3: 10
PotentialFieldControl/Kp_4: 10
PotentialFieldControl/Kp_5: 10
PotentialFieldControl/Kd_0: 5
PotentialFieldControl/Kd_1: 5
PotentialFieldControl/Kd_2: 5
PotentialFieldControl/Kd_3: 1
PotentialFieldControl/Kd_4: 1
PotentialFieldControl/Kd_5: 1
PotentialFieldControl/Ki_0: 0.5
PotentialFieldControl/Ki_1: 0.5
PotentialFieldControl/Ki_2: 0.5
PotentialFieldControl/Ki_3: 0.1
PotentialFieldControl/Ki_4: 0.1
PotentialFieldControl/Ki_5: 0.1
PotentialFieldControl/use_real: true