PotentialFieldControl/desired_hand_pose_right: /right_arm/PotentialFieldControl/desired_hand_right_pose
PotentialFieldControl/desired_hand_pose_left: /left_arm/PotentialFieldControl/desired_hand_left_pose
PotentialFieldControl/Reject_obstacle_left: /left_arm/PotentialFieldControl/Reject_obstacle_list_left
PotentialFieldControl/Reject_obstacle_right: /right_arm/PotentialFieldControl/Reject_obstacle_list_right
PotentialFieldControl/obstacle_list_left: /left_arm/PotentialFieldControl/obstacle_pose_left
PotentialFieldControl/obstacle_list_right: /right_arm/PotentialFieldControl/obstacle_pose_right
PotentialFieldControl/desired_hand_pose_right_filter: /right_arm/PotentialFieldControl/desired_hand_right_filter
PotentialFieldControl/desired_hand_pose_left_filter: /left_arm/PotentialFieldControl/desired_hand_left_filter
PotentialFieldControl/objects_info_r: /right_arm/PotentialFieldControl/objects_info_right
PotentialFieldControl/objects_info_l: /left_arm/PotentialFieldControl/objects_info_left
demo: 0
Number_obj: 5
