PotentialFieldControl/home_desperate_left: /left_arm/PotentialFieldControl/home_left
PotentialFieldControl/home_desperate_right: /right_arm/PotentialFieldControl/home_right
PotentialFieldControl/stop_pub_right:  /right_arm/PotentialFieldControl/stop_pub_filter_right
PotentialFieldControl/stop_pub_left:  /left_arm/PotentialFieldControl/stop_pub_filter_left
trash_left_arm_position_x: -0.75022
trash_left_arm_position_y: -0.47078
trash_left_arm_position_z: 0.54494
trash_left_arm_A_yaw: -0.12690
trash_left_arm_B_pitch: -0.06571
trash_left_arm_C_roll: 0.11774
trash_right_arm_position_x: -1.0
trash_right_arm_position_y: 0.764
trash_right_arm_position_z: 0.513
trash_right_arm_A_yaw: -1.520
trash_right_arm_B_pitch: 0.140
trash_right_arm_C_roll: 2.914
x_treshold: 0.03
y_treshold: 0.03
z_treshold: 0.03
rot_x_treshold: 0.06
rot_y_treshold: 0.06
rot_z_treshold: 0.06