PotentialFieldControl/Kp_0: 800
PotentialFieldControl/Kp_1: 800
PotentialFieldControl/Kp_2: 800
PotentialFieldControl/Kp_3: 800
PotentialFieldControl/Kp_4: 800
PotentialFieldControl/Kp_5: 800
PotentialFieldControl/Kd_0: 200
PotentialFieldControl/Kd_1: 200
PotentialFieldControl/Kd_2: 200
PotentialFieldControl/Kd_3: 200
PotentialFieldControl/Kd_4: 200
PotentialFieldControl/Kd_5: 200
PotentialFieldControl/Ki_0: 0.1
PotentialFieldControl/Ki_1: 0.1
PotentialFieldControl/Ki_2: 0.1
PotentialFieldControl/Ki_3: 0.1
PotentialFieldControl/Ki_4: 0.1
PotentialFieldControl/Ki_5: 0.1
PotentialFieldControl/use_real: false
