PotentialFieldControl/command: /right_arm/PotentialFieldControl/command
PotentialFieldControl/command: /left_arm/PotentialFieldControl/command
PotentialFieldControl/obstacles: /left_arm/PotentialFieldControl/obstacles
PotentialFieldControl/obstacles: /right_arm/PotentialFieldControl/obstacles
PotentialFieldControl/objects_info_r: /right_arm/PotentialFieldControl/objects_info_right
PotentialFieldControl/objects_info_l: /left_arm/PotentialFieldControl/objects_info_left
PotentialFieldControl/error_id: /right_arm/PotentialFieldControl/error_id
PotentialFieldControl/error_id: /left_arm/PotentialFieldControl/error_id
PotentialFieldControl/base_frame: world
demo: 0
Number_obj: 5
#home_position
left_arm_position_x: -1.0
left_arm_position_y: -0.764
left_arm_position_z: 0.513
left_arm_A_yaw: -1.273
left_arm_B_pitch: 0.323
left_arm_C_roll: 2.759
right_arm_position_x: -1.0
right_arm_position_y: 0.764
right_arm_position_z: 0.513
right_arm_A_yaw: -1.520
right_arm_B_pitch: 0.140
right_arm_C_roll: 2.914
#trash_position
trash_left_arm_position_x: -0.75022
trash_left_arm_position_y: -0.47078
trash_left_arm_position_z: 0.54494
trash_left_arm_A_yaw: -1.273
trash_left_arm_B_pitch: 0.323
trash_left_arm_C_roll: 2.759
trash_right_arm_position_x: -1.0
trash_right_arm_position_y: 0.764
trash_right_arm_position_z: 0.513
trash_right_arm_A_yaw: -1.520
trash_right_arm_B_pitch: 0.140
trash_right_arm_C_roll: 2.914
#error_treshold
x_treshold: 0.2
y_treshold: 0.2
z_treshold: 0.2
rot_x_treshold: 0.2
rot_y_treshold: 0.2
rot_z_treshold: 0.2
Info_closed_hand: 0.8
