# make the namespace match the name you use to instantiate the arm in the xacro
left_arm:
  root: world
  tip: left_hand_palm_ref_link
  # joints is not used, since with the robot name and urdf name conventions, the parsing is hardcoded
  # but as a general solution, joint names could be loaded as well, like controllers do
  joints:
  - left_arm_0_joint
  - left_arm_1_joint
  - left_arm_2_joint
  - left_arm_3_joint
  - left_arm_4_joint
  - left_arm_5_joint
  - left_arm_6_joint

# make the namespace match the name you use to instantiate the arm in the xacro
right_arm:
  root: world
  tip: right_hand_palm_ref_link
  # joints is not used, since with the robot name and urdf name conventions, the parsing is hardcoded
  # but as a general solution, joint names could be loaded as well, like controllers do
  joints:
  - right_arm_0_joint
  - right_arm_1_joint
  - right_arm_2_joint
  - right_arm_3_joint
  - right_arm_4_joint
  - right_arm_5_joint
  - right_arm_6_joint