left_arm:
  # CONTROLLERS USED IN THE EXAMLE
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
  PotentialFieldControl:
    type: desperate_housewife/PotentialFieldControl
    root_name: vito_anchor
    tip_name: left_hand_palm_ref_link
    desired_reference_topic: desired_hand_left_pose
    obstacle_remove_topic: Reject_obstacle_list_left
    obstacle_avoidance: obstacle_pose_left
    set_gains_topic: set_gains_left
    time_interp_desired: 5
    pid_left_arm_0_joint: {p: 250,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_left_arm_1_joint: {p: 220,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_left_arm_2_joint: {p: 150,  i: 6, d: 20, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_left_arm_3_joint: {p: 150,  i: 5, d: 12, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_left_arm_4_joint: {p: 90,  i: 5, d: 10, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_left_arm_5_joint: {p: 40,  i: 5, d: 7, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_left_arm_6_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}

right_arm:
  # CONTROLLERS USED IN THE EXAMLE
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  PotentialFieldControl:
    type: desperate_housewife/PotentialFieldControl
    root_name: vito_anchor
    tip_name: right_hand_palm_ref_link
    desired_reference_topic: desired_hand_right_pose
    obstacle_remove_topic: Reject_obstacle_list_right
    obstacle_avoidance: obstacle_pose_right
    set_gains_topic: set_gains_right
    time_interp_desired: 5
    pid_right_arm_0_joint: {p: 250,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_right_arm_1_joint: {p: 220,  i: 10, d: 30, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_right_arm_2_joint: {p: 150,  i: 6, d: 20, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_right_arm_3_joint: {p: 150,  i: 5, d: 12, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_right_arm_4_joint: {p: 90,  i: 5, d: 10, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_right_arm_5_joint: {p: 40,  i: 5, d: 7, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_right_arm_6_joint: {p: 15,  i: 2, d: 5, i_clamp_min: -0.3, i_clamp_max: 0.3}
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint