left_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint

  PotentialFieldControl:
    type: desperate_housewife/PotentialFieldControl
    root_name: world
    tip_name: left_hand_palm_ref_link
    topic_desired_reference: desired_reference
    topic_obstacle: obstacles
    time_interpolation: 5
    max_tau_percentage: 0.5
    pf_repulsive_gain: 0.1
    pf_dist_to_obstacles: 0.15
    pf_dist_to_table: 0.15
    k_p: [110.0, 110.0, 110.0, 110.0, 110.0, 110.0]
    # k_d: [55.0, 55.0, 55.0, 55.0, 55.0, 55.0]
    k_d: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    # k_i: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
    k_i: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # links_with_potential_field: ['left_arm_4_link', 'left_arm_5_link', 'left_arm_6_link', 'left_arm_7_link', 'left_hand_palm_ref_link']
    links_with_potential_field: ['left_arm_4_link', 'left_hand_palm_ref_link']
    enable_joint_limits_avoidance: true
    enable_obstacle_avoidance: true
    enable_attractive_field: true
    enable_null_space: true

left_hand:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - left_hand_synergy_joint

right_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint

  PotentialFieldControl:
    type: desperate_housewife/PotentialFieldControl
    root_name: world
    tip_name: right_hand_palm_ref_link
    # topic_desired_reference: desired_reference
    topic_obstacle: obstacles
    time_interpolation: 5
    max_tau_percentage: 0.5
    pf_repulsive_gain: 0.1
    pf_dist_to_obstacles: 0.1
    pf_dist_to_table: 0.05
    vel_limit_robot: 2
    k_p: [300.0, 300.0, 300.0, 300.0, 300.0, 300.0]
    # k_d: [55.0, 55.0, 55.0, 55.0, 55.0, 55.0]
    k_d: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
    # k_i: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
    k_i: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # links_with_potential_field: ['right_arm_4_link', 'right_arm_5_link', 'right_arm_6_link', 'right_arm_7_link', 'right_hand_palm_ref_link']
    links_with_potential_field: ['right_arm_4_link', 'right_arm_5_link', 'right_arm_6_link', 'right_arm_7_link', 'right_hand_palm_ref_link']
    enable_joint_limits_avoidance: false
    enable_obstacle_avoidance: false
    enable_attractive_field: true
    enable_null_space: false
    enable_interpolation: false

right_hand:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - right_hand_synergy_joint

head:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - head_neck_pitch_joint
      - head_neck_roll_joint
      - head_neck_yaw_joint
      - head_head_tilt_joint
      - head_eyes_tilt_joint
      - head_left_eye_joint
      - head_right_eye_joint

